AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Stream from AWS CloudWatch Logs to splunk's HTTP event collector
Resources:
  SplunkFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Description: Stream events from AWS CloudWatch Logs to Splunk's HTTP event collector
      MemorySize: 512
      Timeout: 30
      Role: 'arn:aws:iam::xxxxyyyyzzzz:role/lambda_basic_execution'
      Environment:
        Variables:
          SPLUNK_HEC_URL: enter_your_value
          SPLUNK_HEC_TOKEN: enter_your_value
      Tags:
        'lambda-console:blueprint': splunk-cloudwatch-logs-processor
  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt 
        - SplunkFunction
        - Arn
      Action: 'lambda:InvokeFunction'
      Principal: 'logs.us-east-1.amazonaws.com'
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Join [ ":", [ "arn:aws:logs:us-east-1", !Ref "AWS::AccountId", "log-group:CloudTrail/AllTrails:*" ] ]
  Subscriptionfilter:
    DependsOn: LambdaInvokePermission
    Type: 'AWS::Logs::SubscriptionFilter'
    Properties: 
      FilterPattern: ""
      DestinationArn: 
        Fn::GetAtt: 
          - "SplunkFunction"
          - "Arn"
      LogGroupName: "CloudTrail/AllTrails"

